[tool.pyflow]
name = "arbejdstimer"
py_version = "3.8"
version = "2021.12.29"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
